config/routes.rb
Pestcloud::Application.routes.draw do
  resources :clients

  devise_for :users

 get 'accounts' => 'pages#accounts'

 root :to => 'pages#home'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :billingaddress, :billingaddresssame, :billingcontactname, :billingemail, :billingphone, :clientname, :contactemail, :contactname, :contactphone, :locationaddress
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :clientname %>
    <%= f.input :locationaddress, as: :text, input_html: { rows: "3" } %>
    <%= f.input :contactname %>
    <%= f.input :contactphone %>
    <%= f.input :contactemail %>
    <%= f.input :billingaddresssame %>
    <%= f.input :billingaddress, as: :text, input_html: { rows: "3" } %>
    <%= f.input :billingcontactname %>
    <%= f.input :billingphone %>
    <%= f.input :billingemail %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<div class="container">
    <h1>All Clients</h1>

    <table class="table-striped table-bordered table-hover">
      <tr>
        <th>Business Name</th>
        <th>Location Address</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Billing Address Same?</th>
        <th>Billing address</th>
        <th>Billing Contact Name</th>
        <th>Billing Phone</th>
        <th>Billing Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @clients.each do |client| %>
      <tr>
        <td><%= client.clientname %></td>
        <td><%= client.locationaddress %></td>
        <td><%= client.contactname %></td>
        <td><%= client.contactphone %></td>
        <td><%= client.contactemail %></td>
        <td><%= client.billingaddresssame %></td>
        <td><%= client.billingaddress %></td>
        <td><%= client.billingcontactname %></td>
        <td><%= client.billingphone %></td>
        <td><%= client.billingemail %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <%= link_to 'New Client', new_client_path %>
</div>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client Name:</b>
  <%= @client.clientname %>
</p>

<p>
  <b>Locationaddress:</b>
  <%= @client.locationaddress %>
</p>

<p>
  <b>Contactname:</b>
  <%= @client.contactname %>
</p>

<p>
  <b>Contactphone:</b>
  <%= @client.contactphone %>
</p>

<p>
  <b>Contactemail:</b>
  <%= @client.contactemail %>
</p>

<p>
  <b>Billingaddresssame:</b>
  <%= @client.billingaddresssame %>
</p>

<p>
  <b>Billingaddress:</b>
  <%= @client.billingaddress %>
</p>

<p>
  <b>Billingcontactname:</b>
  <%= @client.billingcontactname %>
</p>

<p>
  <b>Billingphone:</b>
  <%= @client.billingphone %>
</p>

<p>
  <b>Billingemail:</b>
  <%= @client.billingemail %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<a href="#">PestCloud.com</a>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">PestCloud</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>    
                            <%= link_to 'Clients',  clients_path %>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                              <% if user_signed_in? %>
                                <li><%= link_to "Add +", new_client_path %></li>
                                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                              <% else %>
                            <li><%= link_to "Login", new_user_session_path %></li>
                                <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pestcloud</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

		<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/accounts.html.erb
<h1>Accounts Page</h1>
<p>This is your client page</p>

app/views/pages/clients.html.erb
<h1>Client Page</h1>
<p>This is your client page</p>

app/views/pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to PestCloud</h1>
		<p>
            <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
        </p>
</div>